name: restaurant_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  android_alarm_manager_plus: ^2.0.3
  flutter:
    sdk: flutter
  flutter_local_notifications: ^16.3.2
  http: ^1.2.1
  intl: ^0.19.0
  provider: ^6.1.1
  rxdart: ^0.27.7
  shared_preferences: ^2.2.2
  sqflite: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  test: ^1.24.9
  build_runner: ^2.4.8
  mockito: ^5.4.4

flutter:
  uses-material-design: true

  assets:
    - assets/local_restaurant.json
    - images/